site_name: Bot House
site_description: Official documentation for Bot House.
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: blue
  features:
    - navigation.expand
    - navigation.sections
    - content.code.copy
    - toc.integrate

markdown_extensions:
  - toc:
      toc_depth: 2

extra:
  api: api/

nav:
  - Home: index.md
  - Changelog: changelog/index.md
  - Discord:
    - Home: discord/index.md
    - Getting Started:
        - Quick Start: discord/quickstart.md
    - Functions:
        - Overview: discord/overview.md
        - Embed Functions: discord/embeds.md
        - Messaging: discord/messaging.md
        - User: discord/user.md
  - Api:
    - Home: api/index.md
    - Discord Functions: api/discord/cmd.json
